application: wallace-01
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.application
  login: required
  auth_fail_action: redirect

- url: /js
  static_dir: html_v2/js

- url: /fonts
  static_dir: html_v2/fonts

- url: /fonts/.*\.(otf)$
  static_files: html_v2/fonts/\1
  upload: html_v2/fonts/.*\.(otf)$

- url: /css
  static_dir: html_v2/css

- url: /html
  static_dir: html
  login: required
  auth_fail_action: redirect

- url: /WALLACE_TESTS
  static_dir: WALLACE_TESTS
  login: required
  auth_fail_action: redirect

- url: /includes
  static_dir: includes

- url: /blendMaps
  static_dir: html_v2/blendMaps

- url: /normalMaps
  static_dir: html_v2/normalMaps

- url: /normalMaps/(.*\.(gif|png|jpg|mp4))$
  static_files: html_v2/normalMaps/\1
  upload: html_v2/normalMaps/.*\.(gif|png|jpg|mp4)$

- url: /blendMaps/(.*\.(gif|png|jpg|mp4))$
  static_files: html_v2/blendMaps/\1
  upload: html_v2/blendMaps/.*\.(gif|png|jpg|mp4)$

- url: /WALLACE_TESTS/(.*\.(gif|png|jpg|mp4|vtt))$
  static_files: WALLACE_TESTS/\1
  upload: WALLACE_TESTS/.*\.(gif|png|jpg|mp4|vtt)$
  mime_type: video/mp4
  expiration: "7d"

- url: /(.*\.(gif|png|jpg|jpeg|mp4|vtt))$
  static_files: html_v2/\1
  upload: html_v2/.*\.(gif|png|jpg|jpeg|mp4)$

- url: /(.*\.(html))$
  static_files: html_v2/\1
  upload: html_v2/.*\.(html)$
  login: required
  auth_fail_action: redirect

- url: /.*
  static_files: html_v2/index\.html
  upload: html_v2/index\.html
  login: required
  auth_fail_action: redirect