application: wallace-01
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.application
  login: required
  auth_fail_action: redirect

- url: /js
  static_dir: html/js

- url: /css
  static_dir: html/css

- url: /html
  static_dir: html
  login: required
  auth_fail_action: redirect

- url: /WALLACE_TESTS
  static_dir: WALLACE_TESTS
  login: required
  auth_fail_action: redirect

- url: /includes
  static_dir: includes

- url: /blendMaps
  static_dir: html/blendMaps

- url: /normalMaps
  static_dir: html/normalMaps

- url: /normalMaps/(.*\.(gif|png|jpg|mp4))$
  static_files: html/normalMaps/\1
  upload: html/normalMaps/.*\.(gif|png|jpg|mp4)$

- url: /blendMaps/(.*\.(gif|png|jpg|mp4))$
  static_files: html/blendMaps/\1
  upload: html/blendMaps/.*\.(gif|png|jpg|mp4)$

- url: /WALLACE_TESTS/(.*\.(gif|png|jpg|mp4|vtt))$
  static_files: WALLACE_TESTS/\1
  upload: WALLACE_TESTS/.*\.(gif|png|jpg|mp4|vtt)$
  mime_type: video/mp4

- url: /(.*\.(gif|png|jpg|mp4|vtt))$
  static_files: html/\1
  upload: html/.*\.(gif|png|jpg|mp4)$

- url: /(.*\.(html))$
  static_files: html/\1
  upload: html/.*\.(html)$
  login: required
  auth_fail_action: redirect

- url: /.*
  static_files: html/index\.html
  upload: html/index\.html
  login: required
  auth_fail_action: redirect