application: wallace-01
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.application
  login: required
  auth_fail_action: redirect

- url: /js
  static_dir: html/js

- url: /fonts
  static_dir: html/fonts

- url: /fonts/.*\.(otf)$
  static_files: html/fonts/\1
  upload: html/fonts/.*\.(otf)$

- url: /css
  static_dir: html/css

- url: /html
  static_dir: html
  login: required
  auth_fail_action: redirect

- url: /subtitles
  static_dir: html/subtitles
  login: required
  auth_fail_action: redirect

- url: /includes
  static_dir: includes

- url: /blendMaps
  static_dir: html/blendMaps

- url: /normalMaps
  static_dir: html/normalMaps

- url: /normalMaps/(.*\.(gif|png|jpg|mp4))$
  static_files: html/normalMaps/\1
  upload: html/normalMaps/.*\.(gif|png|jpg|mp4)$

- url: /blendMaps/(.*\.(gif|png|jpg|mp4))$
  static_files: html/blendMaps/\1
  upload: html/blendMaps/.*\.(gif|png|jpg|mp4)$

- url: /subtitles/(.*\.(gif|png|jpg|mp4|vtt))$
  static_files: subtitles/\1
  upload: subtitles/.*\.(gif|png|jpg|mp4|vtt)$
  mime_type: video/mp4
  expiration: "7d"

- url: /720p/(.*\.(mp4))$
  static_files: 720p/\1
  upload: 720p/(.*\.(mp4))$
  mime_type: video/mp4
  expiration: "7d"

- url: /720p/(.*\.(webm))$
  static_files: 720p/\1
  upload: 720p/(.*\.(webm))$
  mime_type: video/webm
  expiration: "7d"

- url: /(.*\.(gif|png|jpg|jpeg|mp4|vtt|svg))$
  static_files: html/\1
  upload: html/.*\.(gif|png|jpg|jpeg|mp4|svg)$

- url: /(.*\.(html))$
  static_files: html/\1
  upload: html/.*\.(html)$
  login: required
  auth_fail_action: redirect

- url: /.*
  static_files: html/index\.html
  upload: html/index\.html
  login: required
  auth_fail_action: redirect