// main-1.0.js - http://github.com/collins1/Mirror
var AzealiaPopcornPlayer=function(a){function b(a,b,c){var d=document.createElement("video");d.setAttribute("type",c);(!0==this.muteVideo||"BackgroundVideo"!=a)&&d.setAttribute("muted","");d.setAttribute("id",a);a=document.createElement("source");a.setAttribute("crossorigin","anonymous");d.setAttribute("crossorigin","anonymous");a.setAttribute("crossOrigin","anonymous");d.setAttribute("crossOrigin","anonymous");a.src=b;d.appendChild(a);d.style.visibility="hidden";d.style.display="none";document.body.appendChild(d);
return d}function f(){var d=c.fmt;c.isVideo?(c.videoFiles=a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+d},"01":{path:"../720p/AB_1_Straight"+d},"02":{path:"../720p/AB_1_Up"+d},"03":{path:"../720p/AB_1_Down"+d},"04":{path:"../720p/AB_1_Left"+d},"05":{path:"../720p/AB_1_Right"+d}},c.videoFiles=supports_crossorigin()?a.videoFiles||{BackgroundVideo:{path:"http://storage.googleapis.com/wallace_videos/AB_BACKGROUND"+d},"01":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Straight"+
d},"02":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Up"+d},"03":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Down"+d},"04":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Left"+d},"05":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Right"+d}}:a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+d},"01":{path:"../720p/AB_1_Straight"+d},"02":{path:"../720p/AB_1_Up"+d},"03":{path:"../720p/AB_1_Down"+d},"04":{path:"..720p/AB_1_Left"+d},"05":{path:"../720p/AB_1_Right"+
d}}):c.videoFiles=a.videoFiles||{BackgroundVideo:{path:"images/black.jpg"},"01":{path:"images/banks_straight.jpg"},"02":{path:"images/banks_up.jpg"},"03":{path:"images/banks_down.jpg"},"04":{path:"images/banks_left.jpg"},"05":{path:"images/banks_right.jpg"}};for(var f in c.videoFiles){var p=b(f,c.videoFiles[f].path,".mp4"==d?"video/mp4":"video/webm");c.videos[f]=Popcorn(p);c.textures[f]=new THREE.Texture(p);c.textures[f].minFilter=THREE.LinearFilter;c.textures[f].magFilter=THREE.LinearFilter;c.textures[f].format=
THREE.RGBFormat;c.textures[f].generateMipmaps=!1;c.videos[f].pause()}c.videos.BackgroundVideo.mute();Popcorn.forEach(c.videos,function(a){a.on("canplaythrough",function(){e++;if(6==e)c.onCanPlayThrough()},!1);a.on("play",function(){g++},!1);a.on("ended",function(){h++;6==h&&(g=h=0,c.videos.BackgroundVideo.play(0),c.onComplete())});a.on("canplayall",function(){this.emit("sync")}).on("sync",function(){6==++k&&(c.onReady(),i.forEach(function(a){c.videos.BackgroundVideo.on(a,function(){if("timeupdate"===
a){if(this.media.paused)for(var b in c.videos)"BackgroundVideo"!==b&&c.videos[b].emit("timeupdate")}else if("play"===a||"pause"===a)for(b in c.videos)if("BackgroundVideo"!==b)c.videos[b][a](c.videos.BackgroundVideo.currentTime())})}))})})}var a=a||{},c={isVideo:a.isVideo||!1,muted:a.muted||!1,verbose:a.verbose||!1,onSubtitlesMade:a.subtitleHander||void 0,videoFiles:void 0,videos:{},textures:{},currentTexture:void 0,fmt:""===Modernizr.video.h264?".webm":".mp4",bufferTime:20,onCanPlayThrough:a.onCanPlayThrough||
function(){},onReady:a.onReady||function(){},onComplete:a.onComplete||function(){}},d={straight:"01",weird:"01",up:"02",down:"03",left:"04",right:"05",tiltLeft:"04",tiltRight:"05",background:"BackgroundVideo"},k=0,e=0,g=0,h=0,i="play pause timeupdate".split(/\s+/g);return{settings:c,setup:function(){f()},sync:function(){if(6<=k&&void 0!==c.currentTexture)c.currentTexture.needsUpdate=!0,c.textures.BackgroundVideo.needsUpdate=!0},play:function(){c.verbose&&console.log("play()");c.muted?c.videos.BackgroundVideo.mute():
c.videos.BackgroundVideo.unmute();c.videos.BackgroundVideo.play()},pause:function(){c.verbose&&console.log("pause()");c.videos.BackgroundVideo.pause()},currentTime:function(){return c.videos.BackgroundVideo.currentTime()},getTexture:function(a){return 6<=e&&(a=d[a],void 0!==c.textures[a])?(c.currentTexture=c.textures[a],c.currentTexture):null}}},AzealiaTracking=function(a){var b=a.width||80,a=a.height||60,f=new THREE.Vector3(0,0,0),c=new THREE.Vector3,d=new jsfeat.pyramid_t(3),k=new jsfeat.pyramid_t(3);
d.allocate(b,a,jsfeat.U8_t|jsfeat.C1_t);k.allocate(b,a,jsfeat.U8_t|jsfeat.C1_t);var e=new Uint8Array(100),g=new Uint8Array(100),h=new Float32Array(40),i=new Float32Array(40),o=new Float32Array(40),v=0.2*b,p=0.8*b,t=p-v,l=0.1*a,y=0.9*a,z=y-l,x=new Float32Array(131),n=new Float32Array(71),r=0,A=0,j;for(j in x)x[j]=Math.random()*t+v;for(j in n)n[j]=Math.random()*z+l;for(j=0;40>j;j+=2)i[j]=THREE.Math.randFloat(v,p),i[j+1]=THREE.Math.randFloat(l,y),o[j]=i[j],o[j+1]=i[j+1];return{update:function(a,b,j){var m=
h;h=i;i=m;m=k;k=d;d=m;jsfeat.imgproc.grayscale(a,b,j,d.data[0]);jsfeat.imgproc.equalize_histogram(d.data[0],d.data[0]);d.build(d.data[0],!0);jsfeat.optical_flow_lk.track(k,d,h,i,20,20,10,e,0.1,0.0010);j=b=a=0;f.set(0,0,0);for(m=0;20>m;m++){b=a+1;if(e[m]&&g[m])f.x+=i[a]-o[a],f.y+=i[b]-o[b],j++,o[a]+=0.0050*(i[a]-o[a]),o[b]+=0.0050*(i[b]-o[b]);else{var u=i,l=a;r=(r+1)%x.length;u[l]=x[r];u=i;l=b;A=(A+1)%n.length;u[l]=x[A];o[a]=i[a];o[b]=i[b]}a+=2;g[m]=e[m]}if(j)f.multiplyScalar(0.1/j),c.x=f.x+0.95*(c.x-
f.x),c.y=f.y+0.95*(c.y-f.y),c.z=f.z+0.95*(c.z-f.z)},width:b,height:a,delta:c,smoothing:0.95}},BackgroundWebcamMaterial=function(a){a=a||{};a={transparent:!1,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{time:{type:"f",value:a.time||0},map:{type:"t",value:a.map},color:{type:"c",value:new THREE.Color(16777215)},opacity:{type:"f",value:void 0!==a.opacity?a.opacity:0},brightnessExpo:{type:"f",value:a.brightnessExpo||1.5}},attributes:{},vertexShader:"varying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nvoid main() {\n\tvUv = vec2(1. - uv.x, 0.749 * uv.y);\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}",
fragmentShader:"uniform sampler2D map;\nvarying vec2 vUv;\nuniform vec3 color;\nuniform float opacity;\nuniform float time;\nuniform float brightnessExpo;\nfloat toGrey(vec3 rgb){\n\treturn dot(rgb, vec3(0.299, 0.587, 0.114));\n}\nfloat getVignette(vec2 uv){\n\treturn pow(1.7 - length(uv*2. - 1.), 2.);\n}\nvoid main()\n{\n\tvec2 s = vec2(1. / 320., 1. / 240.);\n\tfloat g = toGrey(texture2D(map, vUv).xyz) * 3.;\n\tg += toGrey(texture2D(map, vUv + vec2( -s.x, -s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( -s.x, 0.) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( -s.x, s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( s.x, -s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( s.x, 0.) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( s.x, s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( 0., -s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( 0., s.y) ).xyz);\n\tg /= 11.;\n\tg = pow(g * 1.01, brightnessExpo);\n\tgl_FragColor = vec4( getVignette(vUv) * vec3( g ) * color, opacity);\n}"};
THREE.ShaderMaterial.call(this,a)};BackgroundWebcamMaterial.prototype=Object.create(THREE.ShaderMaterial.prototype);
var BlendShader=function(a){a=a||{};a.slits=a.slits||[new THREE.Texture];THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{blendMap:{type:"t",value:a.blendMap||void 0},previousTex:{type:"t",value:a.previousTex||void 0},currentTex:{type:"t",value:a.currentTex||void 0},backgroundTex:{type:"t",value:a.backgroundTex||void 0},mixVal:{type:"f",value:a.mixVal||1},time:{type:"f",value:a.time||0},useBlendMap:{type:"f",value:a.useBlendMap||
1}},vertexShader:"varying vec2 vUv;\nvoid main() {\n\tvUv = uv;\n\tgl_Position = vec4( position, 1.0 );\n}",fragmentShader:"uniform sampler2D blendMap;\nuniform sampler2D backgroundTex;\nuniform sampler2D previousTex;\nuniform sampler2D currentTex;\nuniform float mixVal;\nuniform float useBlendMap;\nuniform float time;\nvarying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nfloat getGray(vec3 rgb)\n{\n\treturn rgb.x * .3 + rgb.x * .59 + rgb.x * .11;\n}\nvoid main()\n{\n\tvec2 alphaUv = vUv * vec2(1., .5);\n\tvec2 colorUv = vUv * vec2(1., .5) + vec2(0., .5);\n\tvec2 bUv = vUv;\n\tbUv.y += time;\n\tbUv.y -= floor(alphaUv.y);\n\tfloat a0 = texture2D(previousTex, alphaUv).x;\n\tfloat a1 = texture2D(currentTex, alphaUv).x;\n\tvec4 p = texture2D(previousTex, colorUv);\n\tvec4 c = texture2D(currentTex, colorUv);\n\tvec4 bg = vec4(1.0,1.0,1.0,0.0);\n\tfloat b = (int(useBlendMap) == 1)? clamp( texture2D(blendMap, bUv).x + (mixVal * 2. - 1.), 0., 1.) : mixVal;\n\tp *= a0;\n\tc *= a1;\n\tvec4 mixed = mix(p, c, b);\n\tgl_FragColor = mixed;\n}"})};
BlendShader.prototype=Object.create(THREE.ShaderMaterial.prototype);
var BlurMotionShader=function(a){a=a||{};a={transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!0,side:a.side||2,uniforms:{map:{type:"t",value:a.map||void 0},previousMap:{type:"t",value:a.previousMap||void 0},decay:{type:"f",value:a.decay||0.75},threshold:{type:"f",value:a.threshold||0.1},width:{type:"f",value:a.width||window.innerWidth},height:{type:"f",value:a.height||window.innerHeight},screendim:{type:"v2",value:a.screendim||new THREE.Vector2(window.innerWidth,window.innerHeight)}},
vertexShader:"uniform float width;\nuniform float height;\nuniform vec2 screendim;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nvarying vec2 vUv;\nvoid main() {\n\tvUv = uv;\n\tvec3 p = position;\n\tgl_Position = vec4( p, 1.0 );\n}",fragmentShader:"uniform sampler2D map;\nuniform sampler2D previousMap;\nuniform float decay;\nvarying vec2 vUv;\nvoid main()\n{\n\tvec4 current = texture2D(map, vUv);\n\tvec4 previous = texture2D(previousMap, vUv);\n\tvec4 color = mix(current, previous, decay) ;\n\tgl_FragColor = color;\n}"};
THREE.ShaderMaterial.call(this,a)};BlurMotionShader.prototype=Object.create(THREE.ShaderMaterial.prototype);
var CameraTexture=function(a){this.video=this.texture=void 0;this.mobile=this.initialized=!1;this.width=320;this.height=240;this.firefoxBug=!1;this.onGetUserMedia=function(){};this.onGetUserMediaFail=function(a){console.log(a,"onGetUserMediaFail... no camera!")};for(var b in a)this[b]=a[b];void 0!==(navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia)?(console.log("Please allow camera access or else use you mouse."),this.init()):console.log("use your mouse to move around")};
CameraTexture.prototype.update=function(){if(this.video.readyState===this.video.HAVE_ENOUGH_DATA)this.texture.needsUpdate=!0};
CameraTexture.prototype.init=function(){this.video=document.createElement("video");this.video.autoplay=!0;this.video.loop=!0;window.URL=window.URL||window.webkitURL;navigator.getUserMedia({video:!0},function(a){this.texture=new THREE.Texture(this.video);this.texture.minFilter=THREE.LinearFilter;this.video&&this.video.mozCaptureStream&&this.video.mozSrcObject?this.video.mozSrcObject=a:this.video.src=window.URL&&window.URL.createObjectURL(a)||a;this.video.play();this.video.setAttribute("width",this.width);
this.video.setAttribute("height",this.height);a=document.createElement("canvas");a.id="webcamCanvas";a.width=this.video.width;a.height=this.video.height;this.canvas=a;this.ctx=a.getContext("2d");this.initialized=!0;this.onGetUserMedia(this.texture)}.bind(this),function(a){this.onGetUserMediaFail(a)}.bind(this));console.log("CameraTexture.prototype.init")};
CameraTexture.prototype.getData=function(){if(this.initialized&&!this.firefoxBug)try{return this.ctx.drawImage(this.video,0,0,this.canvas.width,this.canvas.height),this.ctx.getImageData(0,0,this.canvas.width,this.canvas.height).data}catch(a){if("NS_ERROR_NOT_AVAILABLE"==a.name)this.firefoxBug=!0,setTimeout(function(){this.firefoxBug=!1}.bind(this),100);else throw a;}return[]};function supports_video(){return!0==Modernizr.video}
function supports_crossorigin(){return!supports_video()?!1:void 0!==document.createElement("video").crossOrigin}function supports_h264_baseline_video(){return!supports_video()?!1:""!=Modernizr.video.h264}function timeCodeToInt(a){a=a.split(":");return 3600*a[0]+60*a[1]+1*a[2]}
var AzealiaVideoObject=function(a,b){this.video=void 0!==a.video?a.video:{};if(b)this.texture=a.texture?a.texture:new THREE.Texture(this.video);this.name=a.name||"blank";if(b)this.texture.minFilter=THREE.LinearFilter;if(b)this.texture.magFilter=THREE.LinearFilter;if(b)this.texture.format=THREE.RGBFormat;if(b)this.texture.generateMipmaps=!1;if(b)this.texture.needsUpdate=!1;this.bIsActive=void 0!==a.bIsActive?a.bIsActive:!0;this.bIsActive=a.bIsActive||!1;this.muteVideo=void 0!==a.muteVideo?a.muteVideo:
!1;this.dir=a.dir||new THREE.Vector2(0,0);this.vidAspect=a.aspect||1280/720;this.vidPosition={position:1.0E-4}},MirrorVideoController=function(a){a=a||{};this.doubleWide=a.doubleWide||!1;this.onSubtitlesMade=a.subtitleHander||void 0;this.verbose=a.verbose||!1;this.isVideo=a.isVideo;var b=""!==Modernizr.video.webm?".webm":".mp4";this.isVideo?(this.videoFiles=a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+b},"01":{path:"../720p/AB_1_Straight_1_1"+b},"02":{path:"../720p/AB_1_Up"+b},"03":{path:"../720p/AB_1_Down_1"+
b},"04":{path:"../720p/AB_1_Left_1_2"+b},"05":{path:"../720p/AB_1_Right"+b}},this.videoFiles=supports_crossorigin()?a.videoFiles||{BackgroundVideo:{path:"http://storage.googleapis.com/wallace_videos/AB_BACKGROUND"+b},"01":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Straight_1_1"+b},"02":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Up"+b},"03":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Down_1"+b},"04":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Left_1_2"+
b},"05":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Right"+b}}:a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+b},"01":{path:"../720p/AB_1_Straight_1_1"+b},"02":{path:"../720p/AB_1_Up"+b},"03":{path:"../720p/AB_1_Down_1"+b},"04":{path:"..720p/AB_1_Left_1_2"+b},"05":{path:"../720p/AB_1_Right"+b}}):(console.log("this.isVideo == false"),this.videoFiles=a.videoFiles||{BackgroundVideo:{path:"images/black.jpg"},"01":{path:"images/banks_straight.jpg"},"02":{path:"images/banks_up.jpg"},
"03":{path:"images/banks_down.jpg"},"04":{path:"images/banks_left.jpg"},"05":{path:"images/banks_right.jpg"}});this.videoMap={straight:{t:"01",uOffset:0},weird:{t:"01",uOffset:0},up:{t:"02",uOffset:0},down:{t:"03",uOffset:0},left:{t:"04",uOffset:0},right:{t:"05",uOffset:0},tiltLeft:{t:"04",uOffset:0},tiltRight:{t:"05",uOffset:0},background:{t:"BackgroundVideo",uOffset:0}};this.inverseVideoMap={straight:"01",weird:"01",up:"02",down:"03",left:"04",right:"05",tiltLeft:"04",tiltRight:"05"};this.videos=
{};this.bPaused=!0;this.videoToLoadCount=this.videoLoadCount=0;this.videoDuration=228.351646;this.vidAscpect=1280/720;this.bTransitioning=!1;this.tertiaryVid=this.previousVid=this.currentVid=void 0;this.vidPosition={position:1.0E-4};this.muteVideo=void 0!==a.muteVideo?a.muteVideo:!PLAYING;console.log("this.muteVideo "+this.muteVideo);this.loadVideos(b);$.getJSON(a.subtitles||"../WALLACE_TESTS/subtitles.json",function(a){for(var a=a.entries,b=0;b<a.length;b++)this.createFallMesh(a[b].text,timeCodeToInt(a[b].start));
if(this.onSubtitlesMade)this.onSubtitlesMade(window.textMeshes)}.bind(this));this.muteVideo?this.setVolume(0):this.setVolume(a.volume||0.25);this.restarted=!1};MirrorVideoController.prototype.playVideos=function(){if(this.isVideo)for(var a in this.videos)this.videos[a].video.play();this.bPaused=!1};MirrorVideoController.prototype.pauseVideos=function(){if(this.bPaused)for(var a in this.videos)this.videos[a].video.play();else for(a in this.videos)this.videos[a].video.pause();this.bPaused=!this.bPaused};
MirrorVideoController.prototype.setVideoPosition=function(a){try{for(var b in this.videos)this.videos[b].video.currentTime=a*this.videoDuration}catch(f){}};MirrorVideoController.prototype.setVideoTime=function(a){console.log("MirrorVideoController.prototype.videotime("+a+")");for(var b in this.videos)this.videos[b].video.currentTime=a};MirrorVideoController.prototype.stopVideos=function(){this.setVideoPosition(0);for(var a in this.videos)this.videos[a].video.pause();this.bPaused=!0};
MirrorVideoController.prototype.setVolume=function(a){if(0==a)for(var b in this.videos){if(this.videos[b].video)this.videos[b].video.muted=!1,this.videos[b].video.volume=a}else if(this.videos.BackgroundVideo.video)this.videos.BackgroundVideo.video.muted=!1,this.videos.BackgroundVideo.video.volume=a};
MirrorVideoController.prototype.update=function(){if(!PLAYING&&!this.bPaused){if(0.02<this.vidPosition.position)this.setVideoTime(0),this.videos.BackgroundVideo.video.currentTime=0,window.debugVideo=this.videos.BackgroundVideo}else for(var a=0;a<window.textMeshes.length;a++)if(this.videos.BackgroundVideo.video.currentTime>=window.textMeshes[a].time&&!1==window.textMeshes[a].started)window.textMeshes[a].started=!0,window.textMeshes[a].mesh.rotation.z=0,window.textMeshes[a].mesh.position.y=0.6*-window.innerHeight,
window.textMeshes[a].mesh.position.parent=window.textMeshes[a].mesh,(new TWEEN.Tween(window.textMeshes[a].mesh.position)).to({y:0.75*window.innerHeight},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start().onComplete(function(){this.parent.visible=!1}),(new TWEEN.Tween(window.textMeshes[a].mesh.rotation)).to({z:Math.random()*Math.PI-Math.PI/2},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start();Object.keys(this.videos);for(a in this.videos)if(this.videos[a].bIsActive&&this.videos[a].video.readyState===this.videos[a].video.HAVE_ENOUGH_DATA){if(this.videos[a].texture)this.videos[a].texture.needsUpdate=
!0;if("BackgroundVideo"==a&&this.videos[a].video.readyState)this.vidPosition.position=this.videos[a].video.currentTime/this.videoDuration}};MirrorVideoController.prototype.setVideoActive=function(a,b){if(void 0!=this.inverseVideoMap[a]&&void 0!=this.videos[this.inverseVideoMap[a]])this.videos[this.inverseVideoMap[a]].bIsActive=b};
MirrorVideoController.prototype.loadVideos=function(a){this.videoToLoadCount=this.videoLoadCount=0;for(var b in this.videoFiles)this.isVideo&&this.loadVideo(b,this.videoFiles[b].path,"mp4"==a?"video/mp4":"video/webm");for(b in this.videoFiles)this.videos[b]=this.isVideo?new AzealiaVideoObject({video:document.getElementById(b),name:b,bIsActive:!0},!0):new AzealiaVideoObject({texture:THREE.ImageUtils.loadTexture(this.videoFiles[b].path),name:b,bIsActive:!0},!0);this.playVideos()};
MirrorVideoController.prototype.getVideoLocation=function(a){if(void 0!=this.videoMap[a])return this.videoMap[a];console.log("oops, we couldn't find "+a+" for you.");return this.videoMap.straight};MirrorVideoController.prototype.getVideo=function(a){a=this.getVideoLocation(a);if(this.videos[a.t])return{t:this.videos[a.t].texture,uOffset:a.uOffset};console.error("here comes da beef");return null};
MirrorVideoController.prototype.loadVideo=function(a,b,f,c){var c=c||function(){},d=document.createElement("video");d.setAttribute("loop","");d.setAttribute("type",f);d.setAttribute("preload","auto");(!0==this.muteVideo||"BackgroundVideo"!=a)&&d.setAttribute("muted","");d.setAttribute("id",a);a=document.createElement("source");a.setAttribute("crossorigin","anonymous");d.setAttribute("crossorigin","anonymous");a.setAttribute("crossOrigin","anonymous");d.setAttribute("crossOrigin","anonymous");a.src=
b;d.load();d.appendChild(a);d.style.visibility="hidden";d.style.display="none";d.addEventListener("loadeddata",function(){this.videoLoadCount++;c()}.bind(this),!1);document.body.appendChild(d);if(this.verbose){console.log("verbose");b="abort,canplay,canplaythrough,durationchange,emptied,ended,error,interruptbegin,interruptend,loadeddata,loadedmetadata,loadstart,mozaudioavailable,pause,play,playing,ratechange,seeked,seeking,stalled,suspend,volumechange,waiting".split(",");for(a=0;a<b.length;a++)d.addEventListener(b[a],
function(a){console.log(a.target.id,a.type)},!1)}};MirrorVideoController.prototype.createFallMesh=function(a,b){if(!window.textMeshes)window.textMeshes=[];window.textMeshes.push({started:!1,mesh:new THREE.TextTexture(a,24,"#fff",'"Cardo" serif',"#000",10),time:b})};
var MouthMaterial=function(a){a=a||{};THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{map:{type:"t",value:a.map},aspect:{type:"f",value:a.aspect||0.5625},screenAspect:{type:"f",value:a.screenAspect||window.innerHeight/window.innerWidth},opacity:{type:"f",value:void 0!==a.opacity?a.opacity:1},w:{type:"f",value:1},h:{type:"f",value:1}},attributes:{},vertexShader:"uniform float aspect;\nuniform float screenAspect;\nuniform float w;\nuniform float h;\nvarying vec2 mUv;\nvarying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nvoid main() {\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\tmUv = uv;\n\tvUv.x = mapLinear(gl_Position.x, -w, w, 0., 1.);\n\tvUv.y = mapLinear(gl_Position.y, -h, h, .5, 1.);\n}",
fragmentShader:"uniform sampler2D map;\nuniform float opacity;\nvarying vec2 mUv;\nvarying vec2 vUv;\nvoid main()\n{\n\tfloat alpha = opacity * (1. - pow(length( (mUv*2.-1.) ), 2.));\n\tgl_FragColor = texture2D(map, vUv) * vec4(1., 1., 1., alpha);\n}"})};MouthMaterial.prototype=Object.create(THREE.ShaderMaterial.prototype);
var SlitScan=function(a){function b(a,b,d,c,e,f){j=!1;var g=THREE.ImageUtils.loadTexture(a,void 0,function(){d.drawImage(g.image,0,0,c,e);for(var a=d.getImageData(0,0,c,e).data,h=0,m=0;m<a.length;m+=4)b[h]=a[m]/255,h++;j=!0;g.dispose();void 0!==f&&f()})}function f(){var a=r.image.data,b=0;if(0!==n.length){for(var d=0;d<h;d++)for(var c=0;c<g;c++){var e=4*(d*g+c),b=Math.max(0,Math.floor(q[d*g+c]*(x-1)*z)),b=THREE.Math.clamp(b,0,n.length-10);a[e]=n[b][e+0];a[e+1]=n[b][e+1];a[e+2]=n[b][e+2];a[e+3]=n[b][e+
3]}r.needsUpdate=!0}}function c(){k.render(v,o,A,!0);var a=g,b=h;n.unshift(n.pop());i.readPixels(0,0,a,b,i.RGBA,i.UNSIGNED_BYTE,n[0]);r.needsUpdate=!0}function d(a){q=0==a?I:1==a?K:I}this.width=a.width||320;this.height=a.height||240;this.depth=a.depth||180;var k=a.renderer,a=a.delta||new THREE.Vector3(0,0,0),e=[],g=this.width,h=this.height;if(void 0===k)console.error("SLIT: we need to pass in a renderer!");else{var i=k.getContext(),o=new THREE.OrthographicCamera(-0.5*g,0.5*g,-0.5*h,0.5*h,-1E3,1E3),
v=new THREE.Scene,p=new THREE.DataTexture(new Uint8Array([0,0,0,255]),1,1,THREE.RGBAFormat);p.minFilter=THREE.NearestFilter;p.needsUpdate=!0;var t=new THREE.Mesh(new THREE.PlaneBufferGeometry(g,h),new VideoMaterial({color:16777215,side:2,map:p}));t.visible=!0;t.position=-10;v.add(t);p=new THREE.Mesh(t.geometry,new BackgroundWebcamMaterial({map:p}));p.visible=!1;v.add(p);for(var l=0;l<h;l++)for(var y=0;y<g;y++)e.push(255*y/g),e.push(255*l/h),e.push(255),e.push(0);for(var z=1,x=this.depth,n=[],l=0;l<
x;l++)n[l]=new Uint8Array(e);var r=new THREE.DataTexture(new Uint8Array(e),g,h,THREE.RGBAFormat);r.minFilter=THREE.LinearFilter;r.generateMipmaps=!1;r.needsUpdate=!0;var A=new THREE.WebGLRenderTarget(g,h);A.generateMipmaps=!1;e=document.createElement("canvas");e.id="distortionCanvas";e.width=g;e.height=h;for(var e=e.getContext("2d"),j=!1,I=[],K=[],K=[],q=[],l=0;l<g*h;l++)q[l]=0;b("images/hr_noise.png",I,e,g,h,function(){d(0)});b("images/twoCircleGradient.jpg",K,e,g,h);return{texture:r,delta:a,renderTarget:A,
width:this.width,height:this.height,update:function(){j&&(c(),setTimeout(f,0))},draw:c,setTexture:function(a){t.material.uniforms.map.value=a;t.material.needsUpdate=!0},camera:o,scene:v,videoMesh:t,setDepthSampleScale:function(a){z=a},webcamMesh:p,setDistortion:d}}},THREE=THREE||{};
THREE.TextTexture=function(a,b,f,c,d,k){var k=void 0!==k?k:4,c=void 0!==c?c:"Cardo serif",e=document.createElement("canvas"),g=e.getContext("2d");g.font=b+"pt "+c;var h=g.measureText(a).width;e.width=h+k;e.height=b+2*k;g=e.getContext("2d");g.font=b+"pt "+c;if(void 0!==d)g.fillStyle=d,g.fillRect(e.width/2-h/2-k/2,e.height/2-b/2-+k/2,h+k,b+2*k);g.textAlign="center";g.textBaseline="middle";g.fillStyle=f;g.fillText(a,e.width/2,e.height/2);a=new THREE.Texture(e);a.minFilter=THREE.LinearFilter;a.magFilter=
THREE.LinearFilter;a.format=THREE.RGBFormat;a.generateMipmaps=!1;a.needsUpdate=!0;a=new THREE.MeshBasicMaterial({map:a,color:16777215,side:2,depthTest:!1});e=new THREE.Mesh(new THREE.PlaneBufferGeometry(e.width,e.height,12,7),a);e.doubleSided=!0;e.rotation.x=Math.PI;return e};
var TextureBlendShader=function(a){a=a||{};THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!0,side:a.side||2,uniforms:{blendMap:{type:"t",value:a.blendMap||void 0},previousTex:{type:"t",value:a.previousTex||void 0},currentTex:{type:"t",value:a.currentTex||void 0},mixVal:{type:"f",value:a.mixVal||0.5}},vertexShader:"varying vec2 vUv;\nvoid main() {\n\tvUv = uv;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}",fragmentShader:"uniform sampler2D blendMap;\nuniform sampler2D backgroundTex;\nuniform sampler2D previousTex;\nuniform sampler2D currentTex;\nuniform float mixVal;\nvarying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nfloat getGray(vec3 rgb)\n{\n\treturn rgb.x * .3 + rgb.x * .59 + rgb.x * .11;\n}\nvoid main()\n{\n\tvec4 blendSample = texture2D(blendMap, vUv);\n\tfloat b = blendSample.x;\n\tfloat m = mapLinear(b,0.,1.,.01, .99) > mixVal ? 0. : 1.;//clamp((mixVal * 2. - 1.) + b, 0., 1.);\n\tvec2 pUv = vUv;\n\tvec2 cUv = vUv;// + vec2(0., .4 * (1. - mixVal) * (b*2. - 1.));\n\tvec4 p = texture2D(previousTex, pUv);\n\tvec4 c = texture2D(currentTex, cUv);\n\tvec4 mixed = mix(p, c, m);\n\tgl_FragColor = mixed;\n}"})};
TextureBlendShader.prototype=Object.create(THREE.ShaderMaterial.prototype);var VideoMaterial=function(a){a=a||{};THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{map:{type:"t",value:a.map}},attributes:{},vertexShader:"varying vec2 vUv;\nvarying vec2 vUvAlpha;\nvoid main() {\n\tvUv = vUvAlpha = uv * vec2(1., .5);\n\tvUv.y += .5;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}",fragmentShader:"uniform sampler2D map;\nvarying vec2 vUv;\nvarying vec2 vUvAlpha;\nvoid main()\n{\n\tgl_FragColor = vec4(texture2D(map, vUv).xyz, texture2D(map, vUvAlpha).x);\n}"})};
VideoMaterial.prototype=Object.create(THREE.ShaderMaterial.prototype);
function WebCam(a){var b,f=!1,c,d,k,e,g,h,i,o,v,p,t=[],l=!1,y=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)},z=window.cancelAnimationFrame||window.mozCancelAnimationFrame,x=function(a){1===a.code?console.error("You have denied access to your camera. I cannot do anything."):console.error("getUserMedia() is not supported in your browser.")},n=function(d){b=
a||window.document.createElement("video");b.setAttribute("autoplay",!0);b.setAttribute("width",160);b.setAttribute("height",120);null==navigator.getUserMedia||!HAS_USER_MEDIA?d({code:0}):navigator.getUserMedia({video:!0},function(a){f=!0;c=a;b.src=window.URL.createObjectURL(a);if(a)return!0},d||x)},r=function(){p=y(r.bind(this));this.updatePixels()};this.startCapture=function(a,c){if(!f)n(c),e=b.videoWidth,g=b.videoHeight,h=Math.round(320),i=Math.round(240),d||(d=window.document.createElement("canvas")),
k=d.getContext("2d"),void 0!==a&&!0==a&&r()};this.updatePixels=function(){if(f&&(e=b.videoWidth,g=b.videoHeight,0==h?(h=Math.round(320),i=Math.round(240),d.width=h,d.height=i):d.width=d.width,e&&g)){v=o;k.drawImage(b,0,0,320,240);var a=[],c,n=k.getImageData(0,0,320,240);c=n.data;for(var p=c.length,q=0;q<p;q+=4){var m=0.34*c[q]+0.5*c[q+1]+0.16*c[q+2];a[q/4]=m;c[q]=m;c[q+1]=m;c[q+2]=m}l&&k.putImageData(n,0,0);o=a;t.forEach(function(a){a()})}};this.setGrayscale=function(a){l=a};this.stopCapture=function(){f=
!1;b&&b.pause();c&&c.stop();z(p)};this.onUpdated=function(a){t.push(a)};this.getCurrentPixels=function(){return o};this.getLastPixels=function(){return v};this.getWidth=function(){return h};this.getHeight=function(){return i};this.getDOMElement=function(){return d}}
var app,LYRICS_ON=!1,PLAYING=!1,HAS_PLAYED=!1,HAS_WEBCAM=!1,TEST_WEBCAM=!1,HAS_COORS=supports_crossorigin(),IS_SAFARI=-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome"),iOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1,isMobile=navigator.userAgent.match(/mobile|tablet|ip(ad|hone|od)|android|silk/i)?!0:!1;console.log(navigator.userAgent);
if(!navigator.getUserMedia)navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia||null;var HAS_WEBGL=Modernizr.webgl,HAS_USER_MEDIA=Modernizr.webgl?null===navigator.getUserMedia:!1;$(window).bind("load",function(){THREE.ImageUtils.crossOrigin="";var a="true"==getQuerystring("debug"),b="true"==getQuerystring("useStats"),f="true"==getQuerystring("mute"),c="true"==getQuerystring("auto");app=new APP(b,a,f,c)});
function APP(a,b,f){var c,d,k,e,g,h;function i(a){z();for(var b=0;b<a.length;b++){var c=window.textMeshes[b];LYRICS_ON&&E.add(c.mesh)}}function o(){function a(b,c){if(!window.textMeshes)window.textMeshes=[];window.textMeshes.push({started:!1,mesh:new THREE.TextTexture(b,24,"#fff",'"Cardo" serif',"#000",10),time:c})}y();E.add(C);var b=new THREE.DataTexture(new Uint8Array([0,0,0,255]),1,1,THREE.RGBAFormat);b.minFilter=THREE.NearestFilter;b.needsUpdate=!0;O=new THREE.PlaneBufferGeometry(1,1,12,7);var c=
G.getTexture("background");V=new THREE.MeshBasicMaterial({map:c,color:16777215,side:2});M=new THREE.Mesh(O,V);M.position.z=-10;E.add(M);F=new THREE.Mesh(O,new THREE.MeshBasicMaterial({map:b,color:16777215,side:2,transparent:!0}));U.add(F);D=new THREE.Mesh(new THREE.PlaneBufferGeometry(0.2,0.225),new MouthMaterial({map:G.getTexture("straight"),aspect:0.5625}));D.position.copy(W.straight);F.add(D);c=new THREE.PlaneBufferGeometry(1,4);new THREE.PlaneBufferGeometry(1,4);b=new THREE.Mesh(c,new THREE.MeshBasicMaterial({color:"black",
side:2}));b.position.y=2.5;c=new THREE.Mesh(c,new THREE.MeshBasicMaterial({color:"black",side:2}));c.position.y=-2.5;F.add(b);F.add(c);s=new SlitScan({width:640,height:Math.floor(640/m),depth:isMobile?20:60,renderer:u});J=new AzealiaTracking({width:160,height:120});F.material.map=s.texture;L=new CameraTexture({width:J.width,height:J.height,onGetUserMedia:function(b){j&&console.log("onGetUserMedia: ","success");s.webcamMesh.material.uniforms.map.value=b;TEST_WEBCAM=HAS_WEBCAM=!0;$("#calltoaction").html("Move your face.");
$.getJSON("../WALLACE_TESTS/subtitles.json",function(b){for(var b=b.entries,c=0;c<b.length;c++)a(b[c].text,timeCodeToInt(b[c].start));i&&i(window.textMeshes)})},onGetUserMediaFail:function(b){console.log("onGetUserMediaFail:",b);HAS_WEBCAM=!1;TEST_WEBCAM=!0;$("#calltoaction").html("Move your mouse.");$.getJSON("../WALLACE_TESTS/subtitles.json",function(b){for(var b=b.entries,c=0;c<b.length;c++)a(b[c].text,timeCodeToInt(b[c].start));i&&i(window.textMeshes)})}});b=new THREE.Object3D;b.scale.y=-1;w=
new THREE.Mesh(new THREE.PlaneBufferGeometry(400,400),new THREE.MeshBasicMaterial({transparent:!0,opacity:0.4,map:THREE.ImageUtils.loadTexture("images/face.png"),side:2}));w.scale.set(-1,1,1);w.visible=j;b.add(w);E.add(b);l();$("#play").click(function(){var a=PLAYING;PLAYING=!PLAYING;HAS_PLAYED||(HAS_PLAYED=!0);a||(G.play(),$("#calltoaction").css("opacity","0"),$("#play").css("visibility","hidden"),$("#play").css("display","none"),$("#lyrics").css("visibility","visible"),$("#lyrics").css("display",
"block"),setTimeout(function(){$("#lyrics").css("opacity","1")},5E3),$("#credits").addClass("credits_small"),$("#title").addClass("title_small"),$("#credits").css("opacity","1"),$(".credit").addClass("credit_small"),$(".wallace").addClass("wallace_small"),$(".w").addClass("ws"))});$("#lyrics").click(function(){var a=LYRICS_ON;LYRICS_ON=!LYRICS_ON;for(var b=0;b<window.textMeshes.length;b++)LYRICS_ON?E.add(window.textMeshes[b].mesh):E.remove(window.textMeshes[b].mesh);a?$("#lyrics").html("Lyrics"):
$("#lyrics").html("No Lyrics")});var d=!1;$("#fullcredits").click(function(){(d=!d)?($("#full").css("visibility","visible"),$("#full").css("display","block")):($("#full").css("visibility","hidden"),$("#full").css("display","none"))})}function v(){X||(X=!0,$("#calltoaction").css("opacity","0"),$("#play").css("visibility","visible"),$("#play").css("display","block"),$("#play").css("opacity","1"),$("#overlay").css("opacity","0"),$("#credits").css("opacity","0"),setTimeout(function(){$("#overlay").css("display",
"none");$("#calltoaction").css("display","none");$("#overlay").css("visibility","hidden");$("#calltoaction").css("visibility","hidden")},2500))}function p(){K++;!PLAYING&&Y&&TEST_WEBCAM&&(c+=Math.abs(B.x),d+=Math.abs(B.y),10<c+d&&(Y=!1,v()));s.update();HAS_WEBCAM?(L.update(),J.update(L.getData(),L.width,L.height),B.copy(J.delta)):(N.lerp(new THREE.Vector2(0,0),0.015),B.copy(N),B.x*=3);w.setRotationFromAxisAngle({x:0,y:0,z:1},0.25*B.x);w.position.x=-100*B.x;w.position.y=-150*B.y;P=Math.max(Math.min(1,
50*T.distanceTo(B)),0.985*P);s.setDepthSampleScale(0.5*P+0.5);T.copy(J.delta);G.sync();t();var a=G.currentTime(),b=a>=g&&a<h,a=a>=k&&a<e;if(b||a){if(Q)b?s.setDistortion(0):a&&s.setDistortion(2),s.webcamMesh.visible=!0,s.webcamMesh.material.uniforms.color.value.setRGB(0,0,0),(new TWEEN.Tween(s.webcamMesh.material.uniforms.color.value)).to({r:1,g:1,b:1},500).onUpdate(function(a){s.webcamMesh.material.uniforms.opacity.value=a}).start(),Q=!1;R=!0}else R&&(Q=!0,R=!1,(new TWEEN.Tween(s.webcamMesh.material.uniforms.color.value)).to({r:0,
g:0,b:0},250).onUpdate(function(a){s.webcamMesh.material.uniforms.opacity.value=1-a}).onComplete(function(){s.webcamMesh.visible=!1;s.setDistortion(0)}).start());if(void 0!==window.textMeshes)for(b=0;b<window.textMeshes.length;b++)if(G.currentTime()>=window.textMeshes[b].time&&!1==window.textMeshes[b].started)window.textMeshes[b].started=!0,window.textMeshes[b].mesh.rotation.z=0,window.textMeshes[b].mesh.position.y=0.6*-window.innerHeight,window.textMeshes[b].mesh.position.parent=window.textMeshes[b].mesh,
(new TWEEN.Tween(window.textMeshes[b].mesh.position)).to({y:0.75*window.innerHeight},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start().onComplete(function(){this.parent.visible=!1}),(new TWEEN.Tween(window.textMeshes[b].mesh.rotation)).to({z:Math.random()*Math.PI-Math.PI/2},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start()}function t(){var a=w.position;-110>a.x?(w.material.color.set(16711680),H="left"):110<a.x?(w.material.color.set(255),H="right"):25<a.y?(w.material.color.set(65535),H="up"):-35>a.y?
(w.material.color.set(16776960),H="down"):(w.material.color.set(16777215),H="straight");if(S!==H){var a=H,b=G.getTexture(a);if(null!==b)s.setTexture(b),D.material.uniforms.map.value=b,D.position.copy(W[a]),D.material.uniforms.opacity.value=0,(new TWEEN.Tween(D.material.uniforms.opacity)).to({value:1},500).easing(TWEEN.Easing.Quintic.In).start()}S=H}function l(){var a=window.innerWidth,b=window.innerHeight,c=window.innerWidth/window.innerHeight;c>=m?a*=m/c:b*=c/m;D.material.uniforms.w.value=a/Math.max(1,
window.innerWidth);D.material.uniforms.h.value=b/Math.max(1,window.innerHeight);F.scale.set(a,-b,1);M.scale.set(a,-b,1)}function y(){var a=0.5*window.innerWidth,b=0.5*window.innerHeight;C?(C.left=-a,C.right=a,C.top=-b,C.bottom=b,C.updateProjectionMatrix()):C=new THREE.OrthographicCamera(-a,a,-b,b,-1E3,1E3)}function z(){if(window.textMeshes)for(var a=0;a<window.textMeshes.length;a++){var b=window.textMeshes[a];if(!b.started){var c=Math.random();b.mesh.position.x=0.5<c?0.1*-window.innerWidth-Math.random()*
0.4*window.innerWidth:0.1*window.innerWidth+0.4*Math.random()*window.innerWidth;b.mesh.position.y=0.6*-window.innerHeight;b.mesh.position.z=1}}}function x(){y();l();z();u.setSize(window.innerWidth,window.innerHeight)}function n(a){a.preventDefault();N.set(1+-2*a.clientX/window.innerWidth,-1+2*a.clientY/window.innerHeight)}function r(){}function A(){requestAnimationFrame(A);p();TWEEN.update();HAS_WEBGL&&(u.render(E,C,null,!0),u.render(U,C,null,!1));I&&q.update()}a=document.createElement("div");a.style.position=
"absolute";a.style.left="0px";a.style.top="0px";document.body.appendChild(a);var j=b,I=j,K=0;j&&(console.log("HAS_COORS: "+HAS_COORS),console.log("IS_SAFARI: "+IS_SAFARI));var q,m=1280/720,u,N=new THREE.Vector2,B=new THREE.Vector2,T=new THREE.Vector2,C,E=new THREE.Scene,U=new THREE.Scene,F,G=new AzealiaPopcornPlayer({isVideo:supports_video()&&!isMobile&&HAS_COORS&&!IS_SAFARI?!0:!1,muted:f,subtitleHander:i,onCanPlayThrough:function(){o();this.s=E;window.addEventListener("resize",x,!1);isMobile?(document.addEventListener("touchstart",
n,!1),document.addEventListener("touchmove",n,!1)):(document.addEventListener("mousemove",n,!1),document.addEventListener("keydown",r,!1));A();this.bgm=F},onReady:function(){},onComplete:function(){for(var a=0;a<window.textMeshes.length;a++){var b=window.textMeshes[a];b.started=!1;b.mesh.visible=!0;b.mesh.parent.visible=!0;b.mesh.rotation.z=0}z()}});G.setup();var D,W={straight:new THREE.Vector3(-0.01,-0.18,0.05),left:new THREE.Vector3(-0.07,-0.15,0.05),right:new THREE.Vector3(0.05,-0.15,0.05),up:new THREE.Vector3(-0.0,
-0.1,0.05),down:new THREE.Vector3(0,-0.25,0.05)},S,H=S="doYouLikeHorses?",V,L,s,O,M,J,w,P=0;g=119;h=146;k=162.386;e=191.124;var R=!1,Q=!0,X=!1;c=0;d=0;var Y=!0;!Detector.webgl&&!j&&(HAS_USER_MEDIA=HAS_WEBGL=!1);if(HAS_WEBGL)u=new THREE.WebGLRenderer({antialias:!1,devicePixelRatio:1,alpha:!0}),u.setClearColor(0,0),u.sortObjects=!1,u.setSize(window.innerWidth,window.innerHeight),u.autoClear=!1,a.appendChild(u.domElement),a.style.zIndex=100;if(I)q=new Stats,q.domElement.style.position="absolute",q.domElement.style.top=
"10px",q.domElement.style.left="400px",a.appendChild(q.domElement)}function getQuerystring(a,b){null==b&&(b="");var a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),f=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return null==f?b:f[1]};
