// main-1.0.js - http://github.com/collins1/Mirror
var AzealiaPopcornPlayer=function(a){function b(a,b,c){var d=document.createElement("video");d.setAttribute("type",c);(!0==this.muteVideo||"BackgroundVideo"!=a)&&d.setAttribute("muted","");d.setAttribute("id",a);a=document.createElement("source");a.setAttribute("crossorigin","anonymous");d.setAttribute("crossorigin","anonymous");a.setAttribute("crossOrigin","anonymous");d.setAttribute("crossOrigin","anonymous");a.src=b;d.appendChild(a);d.style.visibility="hidden";d.style.display="none";document.body.appendChild(d);
return d}function f(){var d=c.fmt;c.isVideo?(c.videoFiles=a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+d},"01":{path:"../720p/AB_1_Straight"+d},"02":{path:"../720p/AB_1_Up"+d},"03":{path:"../720p/AB_1_Down"+d},"04":{path:"../720p/AB_1_Left"+d},"05":{path:"../720p/AB_1_Right"+d}},c.videoFiles=supports_crossorigin()?a.videoFiles||{BackgroundVideo:{path:"http://storage.googleapis.com/wallace_videos/AB_BACKGROUND"+d},"01":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Straight"+
d},"02":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Up"+d},"03":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Down"+d},"04":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Left"+d},"05":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Right"+d}}:a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+d},"01":{path:"../720p/AB_1_Straight"+d},"02":{path:"../720p/AB_1_Up"+d},"03":{path:"../720p/AB_1_Down"+d},"04":{path:"..720p/AB_1_Left"+d},"05":{path:"../720p/AB_1_Right"+
d}}):c.videoFiles=a.videoFiles||{BackgroundVideo:{path:"images/black.jpg"},"01":{path:"images/banks_straight.jpg"},"02":{path:"images/banks_up.jpg"},"03":{path:"images/banks_down.jpg"},"04":{path:"images/banks_left.jpg"},"05":{path:"images/banks_right.jpg"}};for(var f in c.videoFiles){var m=b(f,c.videoFiles[f].path,".mp4"==d?"video/mp4":"video/webm");c.videos[f]=Popcorn(m);c.textures[f]=new THREE.Texture(m);c.textures[f].minFilter=THREE.LinearFilter;c.textures[f].magFilter=THREE.LinearFilter;c.textures[f].format=
THREE.RGBFormat;c.textures[f].generateMipmaps=!1;c.videos[f].pause()}c.videos.BackgroundVideo.mute();Popcorn.forEach(c.videos,function(a){a.on("canplaythrough",function(){e++;if(6==e)c.onCanPlayThrough()},!1);a.on("play",function(){g++},!1);a.on("ended",function(){h++;6==h&&(g=h=0,c.videos.BackgroundVideo.play(0),c.onComplete())});a.on("canplayall",function(){this.emit("sync")}).on("sync",function(){6==++j&&(c.onReady(),i.forEach(function(a){c.videos.BackgroundVideo.on(a,function(){if("timeupdate"===
a){if(this.media.paused)for(var b in c.videos)"BackgroundVideo"!==b&&c.videos[b].emit("timeupdate")}else if("play"===a||"pause"===a)for(b in c.videos)if("BackgroundVideo"!==b)c.videos[b][a](c.videos.BackgroundVideo.currentTime())})}))})})}var a=a||{},c={isVideo:a.isVideo||!1,muted:a.muted||!1,verbose:a.verbose||!1,onSubtitlesMade:a.subtitleHander||void 0,videoFiles:void 0,videos:{},textures:{},currentTexture:void 0,fmt:""===Modernizr.video.h264?".webm":".mp4",bufferTime:20,onCanPlayThrough:a.onCanPlayThrough||
function(){},onReady:a.onReady||function(){},onComplete:a.onComplete||function(){}},d={straight:"01",weird:"01",up:"02",down:"03",left:"04",right:"05",tiltLeft:"04",tiltRight:"05",background:"BackgroundVideo"},j=0,e=0,g=0,h=0,i="play pause timeupdate".split(/\s+/g);return{settings:c,setup:function(){f()},sync:function(){if(6<=j&&void 0!==c.currentTexture)c.currentTexture.needsUpdate=!0,c.textures.BackgroundVideo.needsUpdate=!0},play:function(){c.verbose&&console.log("play()");c.muted?c.videos.BackgroundVideo.mute():
c.videos.BackgroundVideo.unmute();c.videos.BackgroundVideo.play()},pause:function(){c.verbose&&console.log("pause()");c.videos.BackgroundVideo.pause()},currentTime:function(){return c.videos.BackgroundVideo.currentTime()},getTexture:function(a){return 6<=e&&(a=d[a],void 0!==c.textures[a])?(c.currentTexture=c.textures[a],c.currentTexture):null}}},AzealiaTracking=function(a){var b=a.width||80,a=a.height||60,f=new THREE.Vector3(0,0,0),c=new THREE.Vector3,d=new jsfeat.pyramid_t(3),j=new jsfeat.pyramid_t(3);
d.allocate(b,a,jsfeat.U8_t|jsfeat.C1_t);j.allocate(b,a,jsfeat.U8_t|jsfeat.C1_t);var e=new Uint8Array(100),g=new Uint8Array(100),h=new Float32Array(40),i=new Float32Array(40),p=new Float32Array(40),t=0.2*b,m=0.8*b,s=m-t,n=0.1*a,w=0.9*a,D=w-n,u=new Float32Array(131),q=new Float32Array(71),k=0,A=0,l;for(l in u)u[l]=Math.random()*s+t;for(l in q)q[l]=Math.random()*D+n;for(l=0;40>l;l+=2)i[l]=THREE.Math.randFloat(t,m),i[l+1]=THREE.Math.randFloat(n,w),p[l]=i[l],p[l+1]=i[l+1];return{update:function(a,b,l){var o=
h;h=i;i=o;o=j;j=d;d=o;jsfeat.imgproc.grayscale(a,b,l,d.data[0]);jsfeat.imgproc.equalize_histogram(d.data[0],d.data[0]);d.build(d.data[0],!0);jsfeat.optical_flow_lk.track(j,d,h,i,20,20,10,e,0.1,0.0010);l=b=a=0;f.set(0,0,0);for(o=0;20>o;o++){b=a+1;if(e[o]&&g[o])f.x+=i[a]-p[a],f.y+=i[b]-p[b],l++,p[a]+=0.0050*(i[a]-p[a]),p[b]+=0.0050*(i[b]-p[b]);else{var n=i,m=a;k=(k+1)%u.length;n[m]=u[k];n=i;m=b;A=(A+1)%q.length;n[m]=u[A];p[a]=i[a];p[b]=i[b]}a+=2;g[o]=e[o]}if(l)f.multiplyScalar(0.1/l),c.x=f.x+0.95*(c.x-
f.x),c.y=f.y+0.95*(c.y-f.y),c.z=f.z+0.95*(c.z-f.z)},width:b,height:a,delta:c,smoothing:0.95}},BackgroundWebcamMaterial=function(a){a=a||{};a={transparent:!1,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{time:{type:"f",value:a.time||0},map:{type:"t",value:a.map},color:{type:"c",value:new THREE.Color(16777215)},opacity:{type:"f",value:void 0!==a.opacity?a.opacity:0},brightnessExpo:{type:"f",value:a.brightnessExpo||1.5}},attributes:{},vertexShader:"varying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nvoid main() {\n\tvUv = vec2(1. - uv.x, 0.749 * uv.y);\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}",
fragmentShader:"uniform sampler2D map;\nvarying vec2 vUv;\nuniform vec3 color;\nuniform float opacity;\nuniform float time;\nuniform float brightnessExpo;\nfloat toGrey(vec3 rgb){\n\treturn dot(rgb, vec3(0.299, 0.587, 0.114));\n}\nfloat getVignette(vec2 uv){\n\treturn pow(1.7 - length(uv*2. - 1.), 2.);\n}\nvoid main()\n{\n\tvec2 s = vec2(1. / 320., 1. / 240.);\n\tfloat g = toGrey(texture2D(map, vUv).xyz) * 3.;\n\tg += toGrey(texture2D(map, vUv + vec2( -s.x, -s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( -s.x, 0.) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( -s.x, s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( s.x, -s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( s.x, 0.) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( s.x, s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( 0., -s.y) ).xyz);\n\tg += toGrey(texture2D(map, vUv + vec2( 0., s.y) ).xyz);\n\tg /= 11.;\n\tg = pow(g * 1.01, brightnessExpo);\n\tgl_FragColor = vec4( getVignette(vUv) * vec3( g ) * color, opacity);\n}"};
THREE.ShaderMaterial.call(this,a)};BackgroundWebcamMaterial.prototype=Object.create(THREE.ShaderMaterial.prototype);
var BlendShader=function(a){a=a||{};a.slits=a.slits||[new THREE.Texture];THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{blendMap:{type:"t",value:a.blendMap||void 0},previousTex:{type:"t",value:a.previousTex||void 0},currentTex:{type:"t",value:a.currentTex||void 0},backgroundTex:{type:"t",value:a.backgroundTex||void 0},mixVal:{type:"f",value:a.mixVal||1},time:{type:"f",value:a.time||0},useBlendMap:{type:"f",value:a.useBlendMap||
1}},vertexShader:"varying vec2 vUv;\nvoid main() {\n\tvUv = uv;\n\tgl_Position = vec4( position, 1.0 );\n}",fragmentShader:"uniform sampler2D blendMap;\nuniform sampler2D backgroundTex;\nuniform sampler2D previousTex;\nuniform sampler2D currentTex;\nuniform float mixVal;\nuniform float useBlendMap;\nuniform float time;\nvarying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nfloat getGray(vec3 rgb)\n{\n\treturn rgb.x * .3 + rgb.x * .59 + rgb.x * .11;\n}\nvoid main()\n{\n\tvec2 alphaUv = vUv * vec2(1., .5);\n\tvec2 colorUv = vUv * vec2(1., .5) + vec2(0., .5);\n\tvec2 bUv = vUv;\n\tbUv.y += time;\n\tbUv.y -= floor(alphaUv.y);\n\tfloat a0 = texture2D(previousTex, alphaUv).x;\n\tfloat a1 = texture2D(currentTex, alphaUv).x;\n\tvec4 p = texture2D(previousTex, colorUv);\n\tvec4 c = texture2D(currentTex, colorUv);\n\tvec4 bg = vec4(1.0,1.0,1.0,0.0);\n\tfloat b = (int(useBlendMap) == 1)? clamp( texture2D(blendMap, bUv).x + (mixVal * 2. - 1.), 0., 1.) : mixVal;\n\tp *= a0;\n\tc *= a1;\n\tvec4 mixed = mix(p, c, b);\n\tgl_FragColor = mixed;\n}"})};
BlendShader.prototype=Object.create(THREE.ShaderMaterial.prototype);
var BlurMotionShader=function(a){a=a||{};a={transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!0,side:a.side||2,uniforms:{map:{type:"t",value:a.map||void 0},previousMap:{type:"t",value:a.previousMap||void 0},decay:{type:"f",value:a.decay||0.75},threshold:{type:"f",value:a.threshold||0.1},width:{type:"f",value:a.width||window.innerWidth},height:{type:"f",value:a.height||window.innerHeight},screendim:{type:"v2",value:a.screendim||new THREE.Vector2(window.innerWidth,window.innerHeight)}},
vertexShader:"uniform float width;\nuniform float height;\nuniform vec2 screendim;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nvarying vec2 vUv;\nvoid main() {\n\tvUv = uv;\n\tvec3 p = position;\n\tgl_Position = vec4( p, 1.0 );\n}",fragmentShader:"uniform sampler2D map;\nuniform sampler2D previousMap;\nuniform float decay;\nvarying vec2 vUv;\nvoid main()\n{\n\tvec4 current = texture2D(map, vUv);\n\tvec4 previous = texture2D(previousMap, vUv);\n\tvec4 color = mix(current, previous, decay) ;\n\tgl_FragColor = color;\n}"};
THREE.ShaderMaterial.call(this,a)};BlurMotionShader.prototype=Object.create(THREE.ShaderMaterial.prototype);
var CameraTexture=function(a){this.video=this.texture=void 0;this.mobile=this.initialized=!1;this.width=320;this.height=240;this.firefoxBug=!1;this.onGetUserMedia=function(){};this.onGetUserMediaFail=function(a){console.log(a,"onGetUserMediaFail... no camera!")};for(var b in a)this[b]=a[b];void 0!==(navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia)?(console.log("Please allow camera access or else use you mouse."),this.init()):console.log("use your mouse to move around")};
CameraTexture.prototype.update=function(){if(this.video.readyState===this.video.HAVE_ENOUGH_DATA)this.texture.needsUpdate=!0};
CameraTexture.prototype.init=function(){this.video=document.createElement("video");this.video.autoplay=!0;this.video.loop=!0;window.URL=window.URL||window.webkitURL;navigator.getUserMedia({video:!0},function(a){this.texture=new THREE.Texture(this.video);this.texture.minFilter=THREE.LinearFilter;this.video&&this.video.mozCaptureStream&&this.video.mozSrcObject?this.video.mozSrcObject=a:this.video.src=window.URL&&window.URL.createObjectURL(a)||a;this.video.play();this.video.setAttribute("width",this.width);
this.video.setAttribute("height",this.height);a=document.createElement("canvas");a.id="webcamCanvas";a.width=this.video.width;a.height=this.video.height;this.canvas=a;this.ctx=a.getContext("2d");this.initialized=!0;this.onGetUserMedia(this.texture)}.bind(this),function(a){this.onGetUserMediaFail(a)}.bind(this));console.log("CameraTexture.prototype.init")};
CameraTexture.prototype.getData=function(){if(this.initialized&&!this.firefoxBug)try{return this.ctx.drawImage(this.video,0,0,this.canvas.width,this.canvas.height),this.ctx.getImageData(0,0,this.canvas.width,this.canvas.height).data}catch(a){if("NS_ERROR_NOT_AVAILABLE"==a.name)this.firefoxBug=!0,setTimeout(function(){this.firefoxBug=!1}.bind(this),100);else throw a;}return[]};function supports_video(){return!0==Modernizr.video}
function supports_crossorigin(){return!supports_video()?!1:void 0!==document.createElement("video").crossOrigin}function supports_h264_baseline_video(){return!supports_video()?!1:""!=Modernizr.video.h264}function timeCodeToInt(a){a=a.split(":");return 3600*a[0]+60*a[1]+1*a[2]}
var AzealiaVideoObject=function(a,b){this.video=void 0!==a.video?a.video:{};if(b)this.texture=a.texture?a.texture:new THREE.Texture(this.video);this.name=a.name||"blank";if(b)this.texture.minFilter=THREE.LinearFilter;if(b)this.texture.magFilter=THREE.LinearFilter;if(b)this.texture.format=THREE.RGBFormat;if(b)this.texture.generateMipmaps=!1;if(b)this.texture.needsUpdate=!1;this.bIsActive=void 0!==a.bIsActive?a.bIsActive:!0;this.bIsActive=a.bIsActive||!1;this.muteVideo=void 0!==a.muteVideo?a.muteVideo:
!1;this.dir=a.dir||new THREE.Vector2(0,0);this.vidAspect=a.aspect||1280/720;this.vidPosition={position:1.0E-4}},MirrorVideoController=function(a){a=a||{};this.doubleWide=a.doubleWide||!1;this.onSubtitlesMade=a.subtitleHander||void 0;this.verbose=a.verbose||!1;this.isVideo=a.isVideo;var b=""!==Modernizr.video.webm?".webm":".mp4";this.isVideo?(this.videoFiles=a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+b},"01":{path:"../720p/AB_1_Straight_1_1"+b},"02":{path:"../720p/AB_1_Up"+b},"03":{path:"../720p/AB_1_Down_1"+
b},"04":{path:"../720p/AB_1_Left_1_2"+b},"05":{path:"../720p/AB_1_Right"+b}},this.videoFiles=supports_crossorigin()?a.videoFiles||{BackgroundVideo:{path:"http://storage.googleapis.com/wallace_videos/AB_BACKGROUND"+b},"01":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Straight_1_1"+b},"02":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Up"+b},"03":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Down_1"+b},"04":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Left_1_2"+
b},"05":{path:"http://storage.googleapis.com/wallace_videos/AB_1_Right"+b}}:a.videoFiles||{BackgroundVideo:{path:"../720p/AB_BACKGROUND"+b},"01":{path:"../720p/AB_1_Straight_1_1"+b},"02":{path:"../720p/AB_1_Up"+b},"03":{path:"../720p/AB_1_Down_1"+b},"04":{path:"..720p/AB_1_Left_1_2"+b},"05":{path:"../720p/AB_1_Right"+b}}):(console.log("this.isVideo == false"),this.videoFiles=a.videoFiles||{BackgroundVideo:{path:"images/black.jpg"},"01":{path:"images/banks_straight.jpg"},"02":{path:"images/banks_up.jpg"},
"03":{path:"images/banks_down.jpg"},"04":{path:"images/banks_left.jpg"},"05":{path:"images/banks_right.jpg"}});this.videoMap={straight:{t:"01",uOffset:0},weird:{t:"01",uOffset:0},up:{t:"02",uOffset:0},down:{t:"03",uOffset:0},left:{t:"04",uOffset:0},right:{t:"05",uOffset:0},tiltLeft:{t:"04",uOffset:0},tiltRight:{t:"05",uOffset:0},background:{t:"BackgroundVideo",uOffset:0}};this.inverseVideoMap={straight:"01",weird:"01",up:"02",down:"03",left:"04",right:"05",tiltLeft:"04",tiltRight:"05"};this.videos=
{};this.bPaused=!0;this.videoToLoadCount=this.videoLoadCount=0;this.videoDuration=228.351646;this.vidAscpect=1280/720;this.bTransitioning=!1;this.tertiaryVid=this.previousVid=this.currentVid=void 0;this.vidPosition={position:1.0E-4};this.muteVideo=void 0!==a.muteVideo?a.muteVideo:!PLAYING;console.log("this.muteVideo "+this.muteVideo);this.loadVideos(b);$.getJSON(a.subtitles||"../WALLACE_TESTS/subtitles.json",function(a){for(var a=a.entries,b=0;b<a.length;b++)this.createFallMesh(a[b].text,timeCodeToInt(a[b].start));
if(this.onSubtitlesMade)this.onSubtitlesMade(window.textMeshes)}.bind(this));this.muteVideo?this.setVolume(0):this.setVolume(a.volume||0.25);this.restarted=!1};MirrorVideoController.prototype.playVideos=function(){if(this.isVideo)for(var a in this.videos)this.videos[a].video.play();this.bPaused=!1};MirrorVideoController.prototype.pauseVideos=function(){if(this.bPaused)for(var a in this.videos)this.videos[a].video.play();else for(a in this.videos)this.videos[a].video.pause();this.bPaused=!this.bPaused};
MirrorVideoController.prototype.setVideoPosition=function(a){try{for(var b in this.videos)this.videos[b].video.currentTime=a*this.videoDuration}catch(f){}};MirrorVideoController.prototype.setVideoTime=function(a){console.log("MirrorVideoController.prototype.videotime("+a+")");for(var b in this.videos)this.videos[b].video.currentTime=a};MirrorVideoController.prototype.stopVideos=function(){this.setVideoPosition(0);for(var a in this.videos)this.videos[a].video.pause();this.bPaused=!0};
MirrorVideoController.prototype.setVolume=function(a){if(0==a)for(var b in this.videos){if(this.videos[b].video)this.videos[b].video.muted=!1,this.videos[b].video.volume=a}else if(this.videos.BackgroundVideo.video)this.videos.BackgroundVideo.video.muted=!1,this.videos.BackgroundVideo.video.volume=a};
MirrorVideoController.prototype.update=function(){if(!PLAYING&&!this.bPaused){if(0.02<this.vidPosition.position)this.setVideoTime(0),this.videos.BackgroundVideo.video.currentTime=0,window.debugVideo=this.videos.BackgroundVideo}else for(var a=0;a<window.textMeshes.length;a++)if(this.videos.BackgroundVideo.video.currentTime>=window.textMeshes[a].time&&!1==window.textMeshes[a].started)window.textMeshes[a].started=!0,window.textMeshes[a].mesh.rotation.z=0,window.textMeshes[a].mesh.position.y=0.6*-window.innerHeight,
window.textMeshes[a].mesh.position.parent=window.textMeshes[a].mesh,(new TWEEN.Tween(window.textMeshes[a].mesh.position)).to({y:0.75*window.innerHeight},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start().onComplete(function(){this.parent.visible=!1}),(new TWEEN.Tween(window.textMeshes[a].mesh.rotation)).to({z:Math.random()*Math.PI-Math.PI/2},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start();Object.keys(this.videos);for(a in this.videos)if(this.videos[a].bIsActive&&this.videos[a].video.readyState===this.videos[a].video.HAVE_ENOUGH_DATA){if(this.videos[a].texture)this.videos[a].texture.needsUpdate=
!0;if("BackgroundVideo"==a&&this.videos[a].video.readyState)this.vidPosition.position=this.videos[a].video.currentTime/this.videoDuration}};MirrorVideoController.prototype.setVideoActive=function(a,b){if(void 0!=this.inverseVideoMap[a]&&void 0!=this.videos[this.inverseVideoMap[a]])this.videos[this.inverseVideoMap[a]].bIsActive=b};
MirrorVideoController.prototype.loadVideos=function(a){this.videoToLoadCount=this.videoLoadCount=0;for(var b in this.videoFiles)this.isVideo&&this.loadVideo(b,this.videoFiles[b].path,"mp4"==a?"video/mp4":"video/webm");for(b in this.videoFiles)this.videos[b]=this.isVideo?new AzealiaVideoObject({video:document.getElementById(b),name:b,bIsActive:!0},!0):new AzealiaVideoObject({texture:THREE.ImageUtils.loadTexture(this.videoFiles[b].path),name:b,bIsActive:!0},!0);this.playVideos()};
MirrorVideoController.prototype.getVideoLocation=function(a){if(void 0!=this.videoMap[a])return this.videoMap[a];console.log("oops, we couldn't find "+a+" for you.");return this.videoMap.straight};MirrorVideoController.prototype.getVideo=function(a){a=this.getVideoLocation(a);if(this.videos[a.t])return{t:this.videos[a.t].texture,uOffset:a.uOffset};console.error("here comes da beef");return null};
MirrorVideoController.prototype.loadVideo=function(a,b,f,c){var c=c||function(){},d=document.createElement("video");d.setAttribute("loop","");d.setAttribute("type",f);d.setAttribute("preload","auto");(!0==this.muteVideo||"BackgroundVideo"!=a)&&d.setAttribute("muted","");d.setAttribute("id",a);a=document.createElement("source");a.setAttribute("crossorigin","anonymous");d.setAttribute("crossorigin","anonymous");a.setAttribute("crossOrigin","anonymous");d.setAttribute("crossOrigin","anonymous");a.src=
b;d.load();d.appendChild(a);d.style.visibility="hidden";d.style.display="none";d.addEventListener("loadeddata",function(){this.videoLoadCount++;c()}.bind(this),!1);document.body.appendChild(d);if(this.verbose){console.log("verbose");b="abort,canplay,canplaythrough,durationchange,emptied,ended,error,interruptbegin,interruptend,loadeddata,loadedmetadata,loadstart,mozaudioavailable,pause,play,playing,ratechange,seeked,seeking,stalled,suspend,volumechange,waiting".split(",");for(a=0;a<b.length;a++)d.addEventListener(b[a],
function(a){console.log(a.target.id,a.type)},!1)}};MirrorVideoController.prototype.createFallMesh=function(a,b){if(!window.textMeshes)window.textMeshes=[];window.textMeshes.push({started:!1,mesh:new THREE.TextTexture(a,24,"#fff",'"Cardo" serif',"#000",10),time:b})};
var MouthMaterial=function(a){a=a||{};THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{map:{type:"t",value:a.map},aspect:{type:"f",value:a.aspect||0.5625},screenAspect:{type:"f",value:a.screenAspect||window.innerHeight/window.innerWidth},opacity:{type:"f",value:void 0!==a.opacity?a.opacity:1},w:{type:"f",value:1},h:{type:"f",value:1}},attributes:{},vertexShader:"uniform float aspect;\nuniform float screenAspect;\nuniform float w;\nuniform float h;\nvarying vec2 mUv;\nvarying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nvoid main() {\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\tmUv = uv;\n\tvUv.x = mapLinear(gl_Position.x, -w, w, 0., 1.);\n\tvUv.y = mapLinear(gl_Position.y, -h, h, .5, 1.);\n}",
fragmentShader:"uniform sampler2D map;\nuniform float opacity;\nvarying vec2 mUv;\nvarying vec2 vUv;\nvoid main()\n{\n\tfloat alpha = opacity * (1. - pow(length( (mUv*2.-1.) ), 2.));\n\tgl_FragColor = texture2D(map, vUv) * vec4(1., 1., 1., alpha);\n}"})};MouthMaterial.prototype=Object.create(THREE.ShaderMaterial.prototype);
var SlitScan=function(a){function b(a,b,d,c,e,f){l=!1;var g=THREE.ImageUtils.loadTexture(a,void 0,function(){d.drawImage(g.image,0,0,c,e);for(var a=d.getImageData(0,0,c,e).data,o=0,h=0;h<a.length;h+=4)b[o]=a[h]/255,o++;l=!0;g.dispose();void 0!==f&&f()})}function f(){var a=k.image.data,b=0;if(0!==q.length){for(var d=0;d<h;d++)for(var c=0;c<g;c++){var e=4*(d*g+c),b=Math.max(0,Math.floor(M[d*g+c]*(u-1)*D)),b=THREE.Math.clamp(b,0,q.length-10);a[e]=q[b][e+0];a[e+1]=q[b][e+1];a[e+2]=q[b][e+2];a[e+3]=q[b][e+
3]}k.needsUpdate=!0}}function c(){j.render(t,p,A,!0);var a=g,b=h;q.unshift(q.pop());i.readPixels(0,0,a,b,i.RGBA,i.UNSIGNED_BYTE,q[0]);k.needsUpdate=!0}function d(a){M=0==a?L:1==a?I:L}this.width=a.width||320;this.height=a.height||240;this.depth=a.depth||180;var j=a.renderer,a=a.delta||new THREE.Vector3(0,0,0),e=[],g=this.width,h=this.height;if(void 0===j)console.error("SLIT: we need to pass in a renderer!");else{var i=j.getContext(),p=new THREE.OrthographicCamera(-0.5*g,0.5*g,-0.5*h,0.5*h,-1E3,1E3),
t=new THREE.Scene,m=new THREE.DataTexture(new Uint8Array([0,0,0,255]),1,1,THREE.RGBAFormat);m.minFilter=THREE.NearestFilter;m.needsUpdate=!0;var s=new THREE.Mesh(new THREE.PlaneBufferGeometry(g,h),new VideoMaterial({color:16777215,side:2,map:m}));s.visible=!0;s.position=-10;t.add(s);m=new THREE.Mesh(s.geometry,new BackgroundWebcamMaterial({map:m}));m.visible=!1;t.add(m);for(var n=0;n<h;n++)for(var w=0;w<g;w++)e.push(255*w/g),e.push(255*n/h),e.push(255),e.push(0);for(var D=1,u=this.depth,q=[],n=0;n<
u;n++)q[n]=new Uint8Array(e);var k=new THREE.DataTexture(new Uint8Array(e),g,h,THREE.RGBAFormat);k.minFilter=THREE.LinearFilter;k.generateMipmaps=!1;k.needsUpdate=!0;var A=new THREE.WebGLRenderTarget(g,h);A.generateMipmaps=!1;e=document.createElement("canvas");e.id="distortionCanvas";e.width=g;e.height=h;for(var e=e.getContext("2d"),l=!1,L=[],I=[],I=[],M=[],n=0;n<g*h;n++)M[n]=0;b("images/hr_noise.png",L,e,g,h,function(){d(0)});b("images/twoCircleGradient.jpg",I,e,g,h);return{texture:k,delta:a,renderTarget:A,
width:this.width,height:this.height,update:function(){l&&(c(),setTimeout(f,0))},draw:c,setTexture:function(a){s.material.uniforms.map.value=a;s.material.needsUpdate=!0},camera:p,scene:t,videoMesh:s,setDepthSampleScale:function(a){D=a},webcamMesh:m,setDistortion:d}}},THREE=THREE||{};
THREE.TextTexture=function(a,b,f,c,d,j){var j=void 0!==j?j:4,c=void 0!==c?c:"Cardo serif",e=document.createElement("canvas"),g=e.getContext("2d");g.font=b+"pt "+c;var h=g.measureText(a).width;e.width=h+j;e.height=b+2*j;g=e.getContext("2d");g.font=b+"pt "+c;if(void 0!==d)g.fillStyle=d,g.fillRect(e.width/2-h/2-j/2,e.height/2-b/2-+j/2,h+j,b+2*j);g.textAlign="center";g.textBaseline="middle";g.fillStyle=f;g.fillText(a,e.width/2,e.height/2);a=new THREE.Texture(e);a.minFilter=THREE.LinearFilter;a.magFilter=
THREE.LinearFilter;a.format=THREE.RGBFormat;a.generateMipmaps=!1;a.needsUpdate=!0;a=new THREE.MeshBasicMaterial({map:a,color:16777215,side:2,depthTest:!1});e=new THREE.Mesh(new THREE.PlaneBufferGeometry(e.width,e.height,12,7),a);e.doubleSided=!0;e.rotation.x=Math.PI;return e};
var TextureBlendShader=function(a){a=a||{};THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!0,side:a.side||2,uniforms:{blendMap:{type:"t",value:a.blendMap||void 0},previousTex:{type:"t",value:a.previousTex||void 0},currentTex:{type:"t",value:a.currentTex||void 0},mixVal:{type:"f",value:a.mixVal||0.5}},vertexShader:"varying vec2 vUv;\nvoid main() {\n\tvUv = uv;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}",fragmentShader:"uniform sampler2D blendMap;\nuniform sampler2D backgroundTex;\nuniform sampler2D previousTex;\nuniform sampler2D currentTex;\nuniform float mixVal;\nvarying vec2 vUv;\nfloat mapLinear( in float x, in float a1, in float a2, in float b1, in float b2 ) {\n\treturn b1 + ( x - a1 ) * ( b2 - b1 ) / ( a2 - a1 );\n}\nfloat getGray(vec3 rgb)\n{\n\treturn rgb.x * .3 + rgb.x * .59 + rgb.x * .11;\n}\nvoid main()\n{\n\tvec4 blendSample = texture2D(blendMap, vUv);\n\tfloat b = blendSample.x;\n\tfloat m = mapLinear(b,0.,1.,.01, .99) > mixVal ? 0. : 1.;//clamp((mixVal * 2. - 1.) + b, 0., 1.);\n\tvec2 pUv = vUv;\n\tvec2 cUv = vUv;// + vec2(0., .4 * (1. - mixVal) * (b*2. - 1.));\n\tvec4 p = texture2D(previousTex, pUv);\n\tvec4 c = texture2D(currentTex, cUv);\n\tvec4 mixed = mix(p, c, m);\n\tgl_FragColor = mixed;\n}"})};
TextureBlendShader.prototype=Object.create(THREE.ShaderMaterial.prototype);var VideoMaterial=function(a){a=a||{};THREE.ShaderMaterial.call(this,{transparent:!0,blending:a.blending||1,depthTest:a.depthTest||!1,side:a.side||2,uniforms:{map:{type:"t",value:a.map}},attributes:{},vertexShader:"varying vec2 vUv;\nvarying vec2 vUvAlpha;\nvoid main() {\n\tvUv = vUvAlpha = uv * vec2(1., .5);\n\tvUv.y += .5;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}",fragmentShader:"uniform sampler2D map;\nvarying vec2 vUv;\nvarying vec2 vUvAlpha;\nvoid main()\n{\n\tgl_FragColor = vec4(texture2D(map, vUv).xyz, texture2D(map, vUvAlpha).x);\n}"})};
VideoMaterial.prototype=Object.create(THREE.ShaderMaterial.prototype);
function WebCam(a){var b,f=!1,c,d,j,e,g,h,i,p,t,m,s=[],n=!1,w=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)},D=window.cancelAnimationFrame||window.mozCancelAnimationFrame,u=function(a){1===a.code?console.error("You have denied access to your camera. I cannot do anything."):console.error("getUserMedia() is not supported in your browser.")},q=function(d){b=
a||window.document.createElement("video");b.setAttribute("autoplay",!0);b.setAttribute("width",160);b.setAttribute("height",120);null==navigator.getUserMedia||!HAS_USER_MEDIA?d({code:0}):navigator.getUserMedia({video:!0},function(a){f=!0;c=a;b.src=window.URL.createObjectURL(a);if(a)return!0},d||u)},k=function(){m=w(k.bind(this));this.updatePixels()};this.startCapture=function(a,c){if(!f)q(c),e=b.videoWidth,g=b.videoHeight,h=Math.round(320),i=Math.round(240),d||(d=window.document.createElement("canvas")),
j=d.getContext("2d"),void 0!==a&&!0==a&&k()};this.updatePixels=function(){if(f&&(e=b.videoWidth,g=b.videoHeight,0==h?(h=Math.round(320),i=Math.round(240),d.width=h,d.height=i):d.width=d.width,e&&g)){t=p;j.drawImage(b,0,0,320,240);var a=[],c,m=j.getImageData(0,0,320,240);c=m.data;for(var q=c.length,k=0;k<q;k+=4){var o=0.34*c[k]+0.5*c[k+1]+0.16*c[k+2];a[k/4]=o;c[k]=o;c[k+1]=o;c[k+2]=o}n&&j.putImageData(m,0,0);p=a;s.forEach(function(a){a()})}};this.setGrayscale=function(a){n=a};this.stopCapture=function(){f=
!1;b&&b.pause();c&&c.stop();D(m)};this.onUpdated=function(a){s.push(a)};this.getCurrentPixels=function(){return p};this.getLastPixels=function(){return t};this.getWidth=function(){return h};this.getHeight=function(){return i};this.getDOMElement=function(){return d}}
var app,LYRICS_ON=!1,PLAYING=!1,HAS_PLAYED=!1,HAS_WEBCAM=!1,TEST_WEBCAM=!1,HAS_COORS=supports_crossorigin(),IS_SAFARI=-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome"),iOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1,isMobile=navigator.userAgent.match(/mobile|tablet|ip(ad|hone|od)|android|silk/i)?!0:!1;console.log(navigator.userAgent);
if(!navigator.getUserMedia)navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia||null;var HAS_WEBGL=Modernizr.webgl,HAS_USER_MEDIA=Modernizr.webgl?null===navigator.getUserMedia:!1;$(window).bind("load",function(){THREE.ImageUtils.crossOrigin="";var a="true"==getQuerystring("debug"),b="true"==getQuerystring("useStats"),f="true"==getQuerystring("mute"),c="true"==getQuerystring("auto");app=new APP(b,a,f,c)});
function APP(a,b,f){var c,d,j,e,g,h;function i(a){k();for(var b=0;b<a.length;b++){var c=window.textMeshes[b];LYRICS_ON&&E.add(c.mesh)}}function p(){s();this.s=E;window.addEventListener("resize",A,!1);isMobile?(document.addEventListener("touchstart",l,!1),document.addEventListener("touchmove",l,!1)):(document.addEventListener("mousemove",l,!1),document.addEventListener("keydown",L,!1));I();this.bgm=F}function t(){}function m(){for(var a=0;a<window.textMeshes.length;a++){var b=window.textMeshes[a];
b.started=!1;b.mesh.visible=!0;b.mesh.parent.visible=!0;b.mesh.rotation.z=0}k()}function s(){function a(b,c){if(!window.textMeshes)window.textMeshes=[];window.textMeshes.push({started:!1,mesh:new THREE.TextTexture(b,24,"#fff",'"Cardo" serif',"#000",10),time:c})}q();E.add(z);var b=new THREE.DataTexture(new Uint8Array([0,0,0,255]),1,1,THREE.RGBAFormat);b.minFilter=THREE.NearestFilter;b.needsUpdate=!0;T=new THREE.PlaneBufferGeometry(1,1,12,7);var c=B.getTexture("background");aa=new THREE.MeshBasicMaterial({map:c,
color:16777215,side:2});Q=new THREE.Mesh(T,aa);Q.position.z=-10;E.add(Q);F=new THREE.Mesh(T,new THREE.MeshBasicMaterial({map:b,color:16777215,side:2,transparent:!0}));ba.add(F);C=new THREE.Mesh(new THREE.PlaneBufferGeometry(0.2,0.225),new MouthMaterial({map:B.getTexture("straight"),aspect:0.5625}));C.position.copy(ca.straight);F.add(C);c=new THREE.PlaneBufferGeometry(1,4);new THREE.PlaneBufferGeometry(1,4);b=new THREE.Mesh(c,new THREE.MeshBasicMaterial({color:"black",side:2}));b.position.y=2.5;c=
new THREE.Mesh(c,new THREE.MeshBasicMaterial({color:"black",side:2}));c.position.y=-2.5;F.add(b);F.add(c);r=new SlitScan({width:640,height:Math.floor(640/P),depth:isMobile?20:60,renderer:x});K=new AzealiaTracking({width:160,height:120});F.material.map=r.texture;N=new CameraTexture({width:K.width,height:K.height,onGetUserMedia:function(b){o&&console.log("onGetUserMedia: ","success");r.webcamMesh.material.uniforms.map.value=b;TEST_WEBCAM=HAS_WEBCAM=!0;$("#calltoaction").html("Move your face.");$.getJSON("../subtitles/subtitles.json",
function(b){for(var b=b.entries,c=0;c<b.length;c++)a(b[c].text,timeCodeToInt(b[c].start));i&&i(window.textMeshes)})},onGetUserMediaFail:function(b){console.log("onGetUserMediaFail:",b);HAS_WEBCAM=!1;TEST_WEBCAM=!0;$("#calltoaction").html("Move your mouse.");$.getJSON("../subtitles/subtitles.json",function(b){for(var b=b.entries,c=0;c<b.length;c++)a(b[c].text,timeCodeToInt(b[c].start));i&&i(window.textMeshes)})}});b=new THREE.Object3D;b.scale.y=-1;v=new THREE.Mesh(new THREE.PlaneBufferGeometry(400,
400),new THREE.MeshBasicMaterial({transparent:!0,opacity:0.4,map:THREE.ImageUtils.loadTexture("images/face.png"),side:2}));v.scale.set(-1,1,1);v.visible=o;b.add(v);E.add(b);u();$("#play").click(function(){var a=PLAYING;PLAYING=!PLAYING;HAS_PLAYED||(HAS_PLAYED=!0);a||(B.play(),$("#calltoaction").css("opacity","0"),$("#play").css("visibility","hidden"),$("#play").css("display","none"),$("#lyrics").css("visibility","visible"),$("#lyrics").css("display","block"),setTimeout(function(){$("#lyrics").css("opacity",
"1")},5E3),$("#credits").addClass("credits_small"),$("#title").addClass("title_small"),$("#credits").css("opacity","1"),$(".credit").addClass("credit_small"),$(".wallace").addClass("wallace_small"),$(".w").addClass("ws"),$(".full").css("visibility","hidden"),$(".full").css("display","none"),$("#cloud").css("visibility","visible"),$("#cloud").css("display","block"),$(".credits_small").css("left",O+"px"),$(".credits_small").css("top",H+"px"),$(".credits_small").css("height",Math.max(200,window.innerHeight-
2*H)+"px"),R=!1)});$("#lyrics").click(function(){var a=LYRICS_ON;LYRICS_ON=!LYRICS_ON;for(var b=0;b<window.textMeshes.length;b++)LYRICS_ON?E.add(window.textMeshes[b].mesh):E.remove(window.textMeshes[b].mesh);a?$("#lyrics").html('<a href="#">Lyrics</a>'):$("#lyrics").html('<a href="#">No Lyrics</a>')});$("#fullcredits").click(function(){(R=!R)?($(".full").css("visibility","visible"),$(".full").css("display","block")):($(".full").css("visibility","hidden"),$(".full").css("display","none"))})}function n(){da||
(da=!0,$("#calltoaction").css("opacity","0"),$("#play").css("visibility","visible"),$("#play").css("display","block"),$("#play").css("opacity","1"),$("#overlay").css("opacity","0"),$("#credits").css("opacity","0"),setTimeout(function(){$("#overlay").css("display","none");$("#calltoaction").css("display","none");$("#overlay").css("visibility","hidden");$("#calltoaction").css("visibility","hidden")},2500))}function w(){fa++;!PLAYING&&ea&&TEST_WEBCAM&&(c+=Math.abs(y.x),d+=Math.abs(y.y),10<c+d&&(ea=!1,
n()));r.update();HAS_WEBCAM?(N.update(),K.update(N.getData(),N.width,N.height),y.copy(K.delta)):(S.lerp(new THREE.Vector2(0,0),0.015),y.copy(S),y.x*=3);v.setRotationFromAxisAngle({x:0,y:0,z:1},0.25*y.x);v.position.x=-100*y.x;v.position.y=-150*y.y;U=Math.max(Math.min(1,50*Z.distanceTo(y)),0.985*U);r.setDepthSampleScale(0.5*U+0.5);Z.copy(K.delta);B.sync();D();var a=B.currentTime(),b=a>=g&&a<h,a=a>=j&&a<e;if(b||a){if(V)b?r.setDistortion(0):a&&r.setDistortion(2),r.webcamMesh.visible=!0,r.webcamMesh.material.uniforms.color.value.setRGB(0,
0,0),(new TWEEN.Tween(r.webcamMesh.material.uniforms.color.value)).to({r:1,g:1,b:1},500).onUpdate(function(a){r.webcamMesh.material.uniforms.opacity.value=a}).start(),V=!1;W=!0}else W&&(V=!0,W=!1,(new TWEEN.Tween(r.webcamMesh.material.uniforms.color.value)).to({r:0,g:0,b:0},250).onUpdate(function(a){r.webcamMesh.material.uniforms.opacity.value=1-a}).onComplete(function(){r.webcamMesh.visible=!1;r.setDistortion(0)}).start());if(void 0!==window.textMeshes)for(b=0;b<window.textMeshes.length;b++)if(B.currentTime()>=
window.textMeshes[b].time&&!1==window.textMeshes[b].started)window.textMeshes[b].started=!0,window.textMeshes[b].mesh.rotation.z=0,window.textMeshes[b].mesh.position.y=0.6*-window.innerHeight,window.textMeshes[b].mesh.position.parent=window.textMeshes[b].mesh,(new TWEEN.Tween(window.textMeshes[b].mesh.position)).to({y:0.75*window.innerHeight},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start().onComplete(function(){this.parent.visible=!1}),(new TWEEN.Tween(window.textMeshes[b].mesh.rotation)).to({z:Math.random()*
Math.PI-Math.PI/2},5E3).easing(TWEEN.Easing.Sinusoidal.Out).start()}function D(){var a=v.position;-110>a.x?(v.material.color.set(16711680),G="left"):110<a.x?(v.material.color.set(255),G="right"):25<a.y?(v.material.color.set(65535),G="up"):-35>a.y?(v.material.color.set(16776960),G="down"):(v.material.color.set(16777215),G="straight");if(X!==G){var a=G,b=B.getTexture(a);if(null!==b)r.setTexture(b),C.material.uniforms.map.value=b,C.position.copy(ca[a]),C.material.uniforms.opacity.value=0,(new TWEEN.Tween(C.material.uniforms.opacity)).to({value:1},
500).easing(TWEEN.Easing.Quintic.In).start()}X=G}function u(){var a=window.innerWidth,b=window.innerHeight,c=window.innerWidth/window.innerHeight;c>=P?a*=P/c:b*=c/P;C.material.uniforms.w.value=a/Math.max(1,window.innerWidth);C.material.uniforms.h.value=b/Math.max(1,window.innerHeight);F.scale.set(a,-b,1);Q.scale.set(a,-b,1);O=(window.innerWidth-a)/2+50;H=(window.innerHeight-b)/2+25;50>O&&(O=50);50>H&&(H=50);$(".credits_small").css("left",O+"px");$(".credits_small").css("top",H+"px");$(".credits_small").css("height",
Math.max(200,window.innerHeight-2*H)+"px")}function q(){var a=0.5*window.innerWidth,b=0.5*window.innerHeight;z?(z.left=-a,z.right=a,z.top=-b,z.bottom=b,z.updateProjectionMatrix()):z=new THREE.OrthographicCamera(-a,a,-b,b,-1E3,1E3)}function k(){if(window.textMeshes)for(var a=0;a<window.textMeshes.length;a++){var b=window.textMeshes[a];if(!b.started){var c=Math.random();b.mesh.position.x=0.5<c?0.1*-window.innerWidth-Math.random()*0.4*window.innerWidth:0.1*window.innerWidth+0.4*Math.random()*window.innerWidth;
b.mesh.position.y=0.6*-window.innerHeight;b.mesh.position.z=1}}}function A(){q();u();k();x.setSize(window.innerWidth,window.innerHeight)}function l(a){a.preventDefault();S.set(1+-2*a.clientX/window.innerWidth,-1+2*a.clientY/window.innerHeight)}function L(){}function I(){requestAnimationFrame(I);w();TWEEN.update();HAS_WEBGL&&(x.render(E,z,null,!0),x.render(ba,z,null,!1));Y&&J.update()}function M(a){isMobile?($("#credits").css("opacity","1"),$("#calltoaction").css("top","40%"),$("#calltoaction").html("Please open on Google Chrome for desktop"),
setTimeout(function(){$("#credits").css("opacity","0");$("#overlay").css("opacity","0");$("#calltoaction").css("opacity","0");setTimeout(function(){$("#creditsContainer").css("display","none");$("#creditsContainer").css("visibility","hidden");$("#credits").css("display","none");$("#credits").css("visibility","hidden");$("#calltoaction").css("display","none");$("#calltoaction").css("visibility","hidden");$("#overlay").css("display","none");$("#overlay").css("visibility","hidden")},2500)},5E3)):(a=
a?"Please make sure your Chrome is up to date and WebGL is enabled":'Please open in <a href="http://www.google.com/chrome">Google Chrome</a>',$("#credits").css("opacity","1"),$("#calltoaction").html(a));$("#calltoaction").css("opacity","1");a=document.createElement("div");a.innerHTML='<iframe width="'+window.innerWidth+'" height="'+window.innerHeight+'" src="https://www.youtube.com/embed/6Gu28S1S64A?loop=1&autoplay=1&autohide=1&showinfo=0" frameborder="0" allowfullscreen></iframe>';a.className="underlay";
document.body.appendChild(a)}a=document.createElement("div");a.style.position="absolute";a.style.left="0px";a.style.top="0px";document.body.appendChild(a);var o=b,Y=o,fa=0,R=!1;o&&(console.log("HAS_COORS: "+HAS_COORS),console.log("IS_SAFARI: "+IS_SAFARI));var J,P=1280/720,x,S=new THREE.Vector2,y=new THREE.Vector2,Z=new THREE.Vector2,O=50,H=25,z,E=new THREE.Scene,ba=new THREE.Scene,F,B,C,ca={straight:new THREE.Vector3(-0.01,-0.18,0.05),left:new THREE.Vector3(-0.07,-0.15,0.05),right:new THREE.Vector3(0.05,
-0.15,0.05),up:new THREE.Vector3(-0.0,-0.1,0.05),down:new THREE.Vector3(0,-0.25,0.05)},X,G=X="doYouLikeHorses?",aa,N,r,T,Q,K,v,U=0;g=119;h=146;j=162.386;e=191.124;var W=!1,V=!0,da=!1;c=0;d=0;var ea=!0;!Detector.webgl&&!o&&(HAS_USER_MEDIA=HAS_WEBGL=!1);b=!!window.chrome;HAS_WEBGL&&b?($("#calltoaction").css("opacity","1"),$("#credits").css("opacity","1"),B=new AzealiaPopcornPlayer({isVideo:supports_video()&&!isMobile&&HAS_COORS&&!IS_SAFARI?!0:!1,muted:f,subtitleHander:i,onCanPlayThrough:p,onReady:t,
onComplete:m}),B.setup(),x=new THREE.WebGLRenderer({antialias:!1,devicePixelRatio:1,alpha:!0}),x.setClearColor(0,0),x.sortObjects=!1,x.setSize(window.innerWidth,window.innerHeight),x.autoClear=!1,a.appendChild(x.domElement),a.style.zIndex=100):M(b,HAS_WEBGL);if(Y)J=new Stats,J.domElement.style.position="absolute",J.domElement.style.top="10px",J.domElement.style.left="400px",a.appendChild(J.domElement)}
function getQuerystring(a,b){null==b&&(b="");var a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),f=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return null==f?b:f[1]};
